### ISSUE TITLE
FoldTree crushing in "Run FoldTree" step

### ISSUE THREAD

**Issue by Nitayah** [DessimozLab/fold_tree#11]
Hi! I am trying to run FoldTree with a zipped folder with ~60 pdb files. Here is my folder:

[all_pdb_files_18.12.23.zip](https://github.com/DessimozLab/fold_tree/files/13703920/all_pdb_files_18.12.23.zip)

The code crashes in "Run Foldtree" branch and returns the following error. I attach it both as an image and as text.

Could you please help me?

![image](https://github.com/DessimozLab/fold_tree/assets/154235258/938eb6ae-061f-4e22-aebf-ad8b69bf7db2)

[Mon Dec 18 12:48:32 2023]
rule dl_ids_sequences:
    input: ./test_40814_3/identifiers.txt
    output: ./test_40814_3/sequence_dataset.csv
    log: ./test_40814_3/logs/dlsequences.log
    jobid: 3
    reason: Missing output files: ./test_40814_3/sequence_dataset.csv
    wildcards: folder=./test_40814_3
    resources: tmpdir=/tmp

Activating conda environment: foldtree

EnvironmentNameNotFound: Could not find conda environment: foldtree
You can list all discoverable environments with `conda info --envs`.

[Mon Dec 18 12:48:37 2023]
Finished job 3.
1 of 15 steps (7%) done
Select jobs to execute...

[Mon Dec 18 12:48:37 2023]
rule dl_ids_structs:
    input: ./test_40814_3/sequence_dataset.csv
    output: ./test_40814_3/sequences.fst, ./test_40814_3/finalset.csv
    log: ./test_40814_3/logs/dlstructs.log
    jobid: 2
    reason: Missing output files: ./test_40814_3/finalset.csv; Input files updated by another job: ./test_40814_3/sequence_dataset.csv
    wildcards: folder=./test_40814_3
    resources: tmpdir=/tmp

Activating conda environment: foldtree

EnvironmentNameNotFound: Could not find conda environment: foldtree
You can list all discoverable environments with `conda info --envs`.

[Mon Dec 18 12:48:39 2023]
Finished job 2.
2 of 15 steps (13%) done
Select jobs to execute...

[Mon Dec 18 12:48:40 2023]
rule plddt:
    input: ./test_40814_3/finalset.csv
    output: ./test_40814_3/plddt.json
    log: ./test_40814_3/logs/plddt.log
    jobid: 1
    reason: Missing output files: ./test_40814_3/plddt.json; Input files updated by another job: ./test_40814_3/finalset.csv
    wildcards: folder=./test_40814_3
    resources: tmpdir=/tmp

Activating conda environment: foldtree

[Mon Dec 18 12:48:40 2023]
rule foldseek_allvall_1:
    input: ./test_40814_3/finalset.csv
    output: ./test_40814_3/allvall_1.csv
    log: ./test_40814_3/logs/foldseekallvall.log
    jobid: 8
    reason: Missing output files: ./test_40814_3/allvall_1.csv; Input files updated by another job: ./test_40814_3/finalset.csv
    wildcards: folder=./test_40814_3
    resources: tmpdir=/tmp

Activating conda environment: foldtree

EnvironmentNameNotFound: Could not find conda environment: foldtree
You can list all discoverable environments with `conda info --envs`.

EnvironmentNameNotFound: Could not find conda environment: foldtree
You can list all discoverable environments with `conda info --envs`.

[Mon Dec 18 12:48:40 2023]
Finished job 8.
3 of 15 steps (20%) done
Select jobs to execute...

[Mon Dec 18 12:48:40 2023]
rule foldseek2distmat:
    input: ./test_40814_3/allvall_1.csv
    output: ./test_40814_3/foldtree_fastmemat.txt, ./test_40814_3/alntmscore_fastmemat.txt, ./test_40814_3/lddt_fastmemat.txt
    log: ./test_40814_3/logs/foldseek2distmat.log
    jobid: 7
    reason: Missing output files: ./test_40814_3/lddt_fastmemat.txt, ./test_40814_3/foldtree_fastmemat.txt, ./test_40814_3/alntmscore_fastmemat.txt; Input files updated by another job: ./test_40814_3/allvall_1.csv
    wildcards: folder=./test_40814_3
    resources: tmpdir=/tmp

Activating conda environment: foldtree

EnvironmentNameNotFound: Could not find conda environment: foldtree
You can list all discoverable environments with `conda info --envs`.

[Mon Dec 18 12:48:42 2023]
Finished job 1.
4 of 15 steps (27%) done
Traceback (most recent call last):
  File "/content/.snakemake/scripts/tmp0mskjfj9.foldseekres2distmat_simple.py", line 9, in <module>
    res = pd.read_table(snakemake.input[0], header = None)
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1282, in read_table
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1723, in _make_engine
    return mapping[engine](f, **self.options)
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "parsers.pyx", line 586, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
[Mon Dec 18 12:48:43 2023]
Error in rule foldseek2distmat:
    jobid: 7
    input: ./test_40814_3/allvall_1.csv
    output: ./test_40814_3/foldtree_fastmemat.txt, ./test_40814_3/alntmscore_fastmemat.txt, ./test_40814_3/lddt_fastmemat.txt
    log: ./test_40814_3/logs/foldseek2distmat.log (check log file(s) for error details)
    conda-env: foldtree

RuleException:
CalledProcessError in file /content/fold_tree/workflow/fold_tree, line 90:
Command 'source /usr/local/bin/activate 'foldtree'; set -euo pipefail;  /usr/local/bin/python3.10 /content/.snakemake/scripts/tmp0mskjfj9.foldseekres2distmat_simple.py' returned non-zero exit status 1.
  File "/content/fold_tree/workflow/fold_tree", line 90, in __rule_foldseek2distmat
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-12-18T124832.269382.snakemake.log
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
[<ipython-input-15-4387aeaa2f49>](https://localhost:8080/#) in <cell line: 1>()
----> 1 get_ipython().run_cell_magic('bash', '-s $jobname $input_type', 'JOBNAME=$1\nINPUT_TYPE=$2\nSUFFIX=""\nif [[ $INPUT_TYPE = "custom" ]]; then\n  mkdir -p "${JOBNAME}/structs"\n  mv "${JOBNAME}/"*.pdb "${JOBNAME}/"*.cif "${JOBNAME}/structs"\n  SUFFIX="custom_structs=True"\nfi\nsnakemake --cores $(nproc --all) --use-conda -s fold_tree/workflow/fold_tree --config folder="./${JOBNAME}" filter=False $SUFFIX  #> /dev/null 2>&1\n#snakemake --cores 4 --use-conda -s fold_tree/workflow/fold_tree --config folder=./${jobname} filter=False\n')

4 frames
<decorator-gen-103> in shebang(self, line, cell)

[/usr/local/lib/python3.10/dist-packages/IPython/core/magics/script.py](https://localhost:8080/#) in shebang(self, line, cell)
    243             sys.stderr.flush()
    244         if args.raise_error and p.returncode!=0:
--> 245             raise CalledProcessError(p.returncode, cell, output=out, stderr=err)
    246 
    247     def _run_script(self, p, cell, to_close):

CalledProcessError: Command 'b'JOBNAME=$1\nINPUT_TYPE=$2\nSUFFIX=""\nif [[ $INPUT_TYPE = "custom" ]]; then\n  mkdir -p "${JOBNAME}/structs"\n  mv "${JOBNAME}/"*.pdb "${JOBNAME}/"*.cif "${JOBNAME}/structs"\n  SUFFIX="custom_structs=True"\nfi\nsnakemake --cores $(nproc --all) --use-conda -s fold_tree/workflow/fold_tree --config folder="./${JOBNAME}" filter=False $SUFFIX  #> /dev/null 2>&1\n#snakemake --cores 4 --use-conda -s fold_tree/workflow/fold_tree --config folder=./${jobname} filter=False\n'' returned non-zero exit status 1.

**Comment by ruthalee** [comment]
I am having the same problem with my custom run. There are closed issues that are similar to this (#3, #6), but I am not sure that those solutions apply here, as they would have been fixed. When I clicked the files tab on the left hand side, my struct folders were empty and the indentifiers.txt files said "1". Thanks for your help!

Input:
Zipped folder containing >100 pdb files.
<img width="741" alt="input" src="https://github.com/DessimozLab/fold_tree/assets/91637333/39f03603-15af-404d-a5d2-9c3c52f1499f">

Error Message:
<img width="1200" alt="Screenshot 2024-01-23 at 6 03 24 PM" src="https://github.com/DessimozLab/fold_tree/assets/91637333/59fb51b6-410d-47be-9464-44c26701aee3">

**Comment by cactuskid** [comment]
this may have been due to using an outdated version of foldseek on the backend. I've changed this parameter on the configfile so it might be working now.

**Comment by msleutel** [comment]
The problem persists for me (tested on 11/04/2024). I get the same error for an "identifier" run as well as a "custom" run


![image](https://github.com/DessimozLab/fold_tree/assets/95013201/9601ce51-9c43-456e-bdee-f3a514fe2e45)

**Comment by trinicordero** [comment]
I am having the same problem (17/05/24) :( pleaseeee help!

**Comment by KeaunAmani** [comment]
The issue persists for me as well. Seems that the foldseek code is bugged currently for custom structures and has been bugged for a while.

**Comment by pck00** [comment]
Same/similar issue:

I've ran foldtree successfully with a local install using the option to download files from the identifiers.txt file. Then I delete the output, leave the downloaded pdbs in the generated folder and simply add the custom_structs=True flag. 
Same/similar errors as people using the google colab sheet. So clearly nothing is wrong with the input, and it must be a rather simple bug? I'd love to be able to use the program again so a fix would be much appreciated :)

custom structures, skipping download of structures
myfam/structs/ already exists
myfam/rejected/ already exists
Traceback (most recent call last):
  File "/home/pck/fold_tree-main/.snakemake/scripts/tmpnwjgtu90.dl_structs.py", line 70, in <module>
    seqdf = pd.read_csv(snakemake.input[0])
  File "/home/pck/anaconda3/envs/foldtree/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/pck/anaconda3/envs/foldtree/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/pck/anaconda3/envs/foldtree/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/pck/anaconda3/envs/foldtree/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1898, in _make_engine
    return mapping[engine](f, **self.options)
  File "/home/pck/anaconda3/envs/foldtree/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "parsers.pyx", line 581, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
[Fri Jan 17 12:30:37 2025]
Error in rule dl_ids_structs:
    jobid: 2
    input: myfam/sequence_dataset.csv
    output: myfam/finalset.csv
    log: myfam/logs/dlstructs.log (check log file(s) for error details)
    conda-env: foldtree

RuleException:
CalledProcessError in file /home/pck/fold_tree-main/workflow/fold_tree, line 156:
Command 'source /home/pck/anaconda3/bin/activate 'foldtree'; set -euo pipefail;  python /home/pck/fold_tree-main/.snakemake/scripts/tmpnwjgtu90.dl_structs.py' returned non-zero exit status 1.
  File "/home/pck/fold_tree-main/workflow/fold_tree", line 156, in __rule_dl_ids_structs
  File "/home/pck/anaconda3/envs/foldtree/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Removing output files of failed job dl_ids_structs since they might be corrupted:
myfam/finalset.csv
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2025-01-17T123031.674321.snakemake.log

**Comment by cactuskid** [comment]
i think i tracked it down. Please give it a shot now. sorry for the inconvenience

**Comment by pck00** [comment]
It works, horray! Thanks for the amazing tool!
